//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PompInspector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PompInspector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmperageLabel.
        /// </summary>
        public static string AmperageLabel {
            get {
                return ResourceManager.GetString("AmperageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName1.
        /// </summary>
        public static string ComboBoxItemName1 {
            get {
                return ResourceManager.GetString("ComboBoxItemName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName2.
        /// </summary>
        public static string ComboBoxItemName2 {
            get {
                return ResourceManager.GetString("ComboBoxItemName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName3.
        /// </summary>
        public static string ComboBoxItemName3 {
            get {
                return ResourceManager.GetString("ComboBoxItemName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName4.
        /// </summary>
        public static string ComboBoxItemName4 {
            get {
                return ResourceManager.GetString("ComboBoxItemName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName5.
        /// </summary>
        public static string ComboBoxItemName5 {
            get {
                return ResourceManager.GetString("ComboBoxItemName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName6.
        /// </summary>
        public static string ComboBoxItemName6 {
            get {
                return ResourceManager.GetString("ComboBoxItemName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName7.
        /// </summary>
        public static string ComboBoxItemName7 {
            get {
                return ResourceManager.GetString("ComboBoxItemName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComboBoxItemName8.
        /// </summary>
        public static string ComboBoxItemName8 {
            get {
                return ResourceManager.GetString("ComboBoxItemName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfirmButtonText.
        /// </summary>
        public static string ConfirmButtonText {
            get {
                return ResourceManager.GetString("ConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CubicMeterPerHourLabel.
        /// </summary>
        public static string CubicMeterPerHourLabel {
            get {
                return ResourceManager.GetString("CubicMeterPerHourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateLabel.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinalStateLabel.
        /// </summary>
        public static string FinalStateLabel {
            get {
                return ResourceManager.GetString("FinalStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateRaportButtonText.
        /// </summary>
        public static string GenerateRaportButtonText {
            get {
                return ResourceManager.GetString("GenerateRaportButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitialStateLabel.
        /// </summary>
        public static string InitialStateLabel {
            get {
                return ResourceManager.GetString("InitialStateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PompLabel.
        /// </summary>
        public static string PompLabel {
            get {
                return ResourceManager.GetString("PompLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PompRuntimeLabel.
        /// </summary>
        public static string PompRuntimeLabel {
            get {
                return ResourceManager.GetString("PompRuntimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductionLabel.
        /// </summary>
        public static string ProductionLabel {
            get {
                return ResourceManager.GetString("ProductionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VoltageLabel.
        /// </summary>
        public static string VoltageLabel {
            get {
                return ResourceManager.GetString("VoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WindowTitle.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
